name: hotel_booking
description: A new Flutter project.
publish_to: none
version: 1.2.3
environment:
    sdk: '>=2.19.6 <3.0.0'
dependencies:
    animated_theme_switcher: ^2.0.8
    connectivity_plus: ^5.0.1
    device_preview: ^1.1.0
    # flutter_web: any
    # flutter_web_ui: any
    dio: ^5.3.3
    dropdown_button2: ^2.1.4
    fancy_containers: ^0.0.5
    flutter:
     
        sdk: flutter
    flutter_local_notifications: ^16.1.0
    flutter_localizations:
        sdk: flutter  
    flutter_multi_formatter: ^2.11.11
    flutter_secure_storage: ^8.1.0
    flutter_settings_ui: ^2.0.1
    font_awesome_flutter: ^10.4.0
    form_field_validator: ^1.1.0
    form_validator: ^2.1.1
    google_fonts: ^4.0.4
    intl: any
    intl_translation: ^0.18.0
    multi_validator: ^1.0.1
    multiple_result: ^4.0.0
    outline_gradient_button: ^2.0.1+1
    provider: ^6.0.5
    pull_to_refresh: ^2.0.0
    readmore: ^2.2.0
    rflutter_alert: ^2.0.7
    shared_preferences: ^2.2.1
    shimmer: ^3.0.0
    sqflite: ^2.2.8+4
    url_launcher: ^6.1.11
    workmanager: ^0.5.1
    xen_popup_card: ^0.0.1
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
flutter:
    generate: true 
    uses-material-design: true
    # The following section is specific to Flutter.
    assets: 
     - assets/
     - assets/images/
    fonts: 
      - family: Quicksand
        fonts: 
            - asset: assets/fonts/QuicksandBold.ttf
              weight: 700
            - asset: assets/fonts/QuicksandMedium.ttf
              weight: 500
            - asset: assets/fonts/QuicksandSemiBold.ttf
              weight: 400
    
   # Add this line


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages